### ISSUE TITLE
http://repo.or.cz/w/siplcs.git new sipe repo?

### ISSUE THREAD

**Issue by joakim-tjernlund** [tieto/sipe#134]
I see that http://repo.or.cz/w/siplcs.git has gotten support for Desktop Sharing, is this repo 
preferred now?

**Comment by xhaakon** [comment]
http://repo.or.cz/w/siplcs.git is and always has been official repository for Sipe from which stable releases (i.e. those that are packaged in GNU/Linux distributions) are made. Anything you find here on GitHub that is not included in the official git is considered experimental features.

Contributing desktop sharing (only the viewer part so far) was a long overdue task for me and it just finally happened that I had the time to go through my code, fix remaining issues and push it upstream so that not only those who use sipe-collab PPA can benefit from it.

> is this repo preferred now?

If you're installing from the PPA, I recommend you stay with the GitHub repo for now, because there are still some features not in official Sipe yet (presenting your own desktop mainly). The goal is to get as much of the code as possible upstream, but that's still a work in progress.
