### ISSUE TITLE
Latest pidgin-sipe package for 14.04 is broken

### ISSUE THREAD

**Issue by tomgl** [tieto/sipe#169]
This package is broken, it's almost empty (there are only doc files left in the .deb file):
pidgin-sipe - `1.23.0+sipe-0+201712190934~ubuntu14.04.1`
https://launchpad.net/~sipe-collab/+archive/ubuntu/ppa/+sourcepub/8581143/+listing-archive-extra

The previous build for 14.04 was fine:
pidgin-sipe - `1.22.1+sipe-0+201710201543~ubuntu14.04.1`
https://launchpad.net/%7Esipe-collab/+archive/ubuntu/ppa/+sourcepub/8377055/+listing-archive-extra

In the diff file, I see that the `debian/pidgin-sipe.install` has been removed:
https://launchpadlibrarian.net/349747125/pidgin-sipe_1.22.1+sipe-0+201710201543~ubuntu14.04.1_1.23.0+sipe-0+201712190934~ubuntu14.04.1.diff.gz

From what I can tell (without testing them), the 16.04 package seems OK (it contains binaries).
Comparing the build logs beetween this two packages gives some clues:

- 16.04: https://launchpadlibrarian.net/349744087/buildlog_ubuntu-xenial-amd64.pidgin-sipe_1.23.0+sipe-0+201712190836~ubuntu16.04.1_BUILDING.txt.gz
=> binaries are installed into `/<<BUILDDIR>>/pidgin-sipe-1.23.0+sipe/debian/pidgin-sipe/usr/...` (which I guess is right to get files into the .deb package)

- 14.04: https://launchpadlibrarian.net/349752375/buildlog_ubuntu-trusty-amd64.pidgin-sipe_1.23.0+sipe-0+201712190934~ubuntu14.04.1_BUILDING.txt.gz
=> binaries are installed into `/<<BUILDDIR>>/pidgin-sipe-1.23.0+sipe/debian/tmp/usr/...`

**Comment by xhaakon** [comment]
On 14.04 the files get installed into `debian/tmp` because, unlike the other versions, 14.04 build creates two binary packages - `pidgin-sipe` and `pidgin-sipe-dbg`. Therefore we still need `debian/pidgin-sipe.install` to tell dpkg which files should go into which package. Without it `pidgin-sipe` ends up empty as you're seeing.

I have put the install file back and triggered a rebuild. The package looks good to me now. Please reinstall from the PPA.

**Comment by tomgl** [comment]
Thanks for the changes you've made. I've just upgraded to `1.23.0+sipe-0+201712300216~ubuntu14.04.1` and it works fine now.  I think you can close this issue.
