### ISSUE TITLE
Pidgin can't open file transfers when a space is in the file name

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#69]
reported issue from user.

**Comment by xhaakon** [comment]
I read this issue as:

_When I select a received file in File Transfers dialog and click Open, nothing happens or a browser window opens with a misshapen URL like `file:///tmp/some%2520file.jpg`_

Turns out the logic in Pidgin that chooses which file viewer to use is quite complex and its behavior depends on running desktop environment and user settings. I assume the user experiences the same problems I've encountered on clean Ubuntu 16.04, which is what I have fixed.

You may test the following packages:

```
pidgin - 1:3.0.0~collab-1+201605120812~ubuntu16.10.1
pidgin - 1:3.0.0~collab-1+201605120809~ubuntu16.04.1
pidgin - 1:3.0.0~collab-1+201605120810~ubuntu15.10.1
pidgin - 1:3.0.0~collab-1+201605120810~ubuntu15.04.1
pidgin - 1:3.0.0~collab-1+201605120809~ubuntu14.04.1 
```

If you still can't open the file, please attach Pidgin **verbose** log:

```
PURPLE_VERBOSE_DEBUG=1 pidgin --debug
```

**Comment by tmuehlhoff** [comment]
Verified ok
