### ISSUE TITLE
Regarding:Release notes of the builds

### ISSUE THREAD

**Issue by tcprdg** [tieto/sipe#74]
Hi,

Every day (i mean whenever there is an update available on pidgin-sipe), I keep updating it and using it. But I dont know where to find the release notes for that particular version. Appreciate if the release notes get published and if its  already there, please point me to that.

Also, what kind of regression testing is performed to make sure nothing  breaks whenever new bugs are fixed and new version  released?

**Comment by xnandersson** [comment]
@tcprdg Our repository here on Github is mainly for our own Work-in-progress where we develop and later refine the code for inclusion upstream. We work with the aim that the release notes will come from the upstream projects where our features are present.

 File Transfer was recently upstreamed to SIPE for example and featured in version 1.21, and we hope video will be next. We are also waiting for other upstream projects to mature, like the release of FreeRDP 2.0, hopefully happening later this year, so we can upstream Desktop Screen Sharing.

 We work very rapidly, and instead of release notes we use the issue tracker where we tag issues with "ready for testing". That is how we communicate the latest changes that are supposed to work in the latest build.

 As for regression testing we don't have anything automated, but whenever upstream projects demands unit testing we implement them. Like the case with Farstream and libnice.
